# Generated by Django 4.2 on 2025-04-14 20:47

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staffs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_job', models.CharField(blank=True, max_length=40, null=True)),
                ('staff_surname', models.CharField(blank=True, max_length=150, null=True)),
                ('staff_name', models.CharField(blank=True, max_length=150, null=True)),
                ('color', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=[('#FFFFFF', 'white'), ('#000000', 'black')])),
            ],
        ),
    ]
