# Generated by Django 4.2 on 2025-04-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_surname', models.CharField(blank=True, max_length=150, null=True)),
                ('client_name', models.CharField(blank=True, max_length=150, null=True)),
                ('client_fathername', models.CharField(blank=True, max_length=150, null=True)),
                ('client_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('client_auto', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
