# Generated by Django 4.2 on 2025-04-14 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '__first__'),
        ('Staff', '0001_initial'),
        ('Property', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Property.property')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('mode', models.CharField(blank=True, choices=[('active', 'Активная'), ('created', 'Созданная'), ('complete', 'Завершенная')], default='created', max_length=100, null=True)),
                ('works', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.clients')),
                ('props', models.ManyToManyField(to='Dashboard.propertytasks')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Staff.staffs')),
            ],
        ),
    ]
