# Generated by Django 4.2 on 2025-04-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_alter_tasks_props'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='props',
            field=models.ManyToManyField(blank=True, to='Dashboard.propertytasks'),
        ),
    ]
