# Generated by Django 4.2 on 2025-04-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop_name', models.CharField(blank=True, max_length=150, null=True)),
                ('prop_cost', models.IntegerField(blank=True, null=True)),
                ('prop_col', models.IntegerField(blank=True, null=True)),
                ('prop_allcost', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
