# Generated by Django 4.2 on 2025-04-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='prop_position',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
